apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc  # Имя сервиса
  labels:
    app.kubernetes.io/name: demo
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}  # ClusterIP/NodePort/LoadBalancer
  ports:
    - port: {{ .Values.service.port }}       # Внешний порт (49340)
      targetPort: {{ .Values.service.targetPort }}  # Порт контейнера (8080)
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: demo            # Должно совпадать с метками Pod в deployment.yaml
    app.kubernetes.io/instance: {{ .Release.Name }}