# values.yaml - Конфигурация Helm-чарта для приложения demo

# Настройки образа Docker
image:
  repository: danilkhasanov/demo  # Имя образа в реестре
  tag: latest                     # Тег образа (можно заменить на ${{ github.sha }} в CI)
  pullPolicy: IfNotPresent        # Политика загрузки образа

# Настройки развертывания
replicaCount: 1                   # Количество реплик
resources:                        # Лимиты ресурсов
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

# Настройки сервиса
service:
  type: NodePort
  port: 8080
  targetPort: 8080
  nodePort: 30080  # Порт на ноде (диапазон 30000-32767)

ingress:
  enabled: true
  hosts:
    - host: demo.localhost
      paths:
        - path: /
          pathType: Prefix