# values.yaml - Конфигурация Helm-чарта для приложения demo

# Настройки образа Docker
image:
  repository: danilkhasanov/demo  # Имя образа в реестре
  tag: latest                     # Тег образа (можно заменить на ${{ github.sha }} в CI)
  pullPolicy: IfNotPresent        # Политика загрузки образа

# Настройки развертывания
replicaCount: 1                   # Количество реплик
resources:                        # Лимиты ресурсов
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

# Настройки сервиса
service:
  type: ClusterIP                 # Тип сервиса (ClusterIP/NodePort/LoadBalancer)
  port: 6443                   # Внешний порт сервиса (который вы хотите использовать)
  targetPort: 49340                # Порт контейнера (должен совпадать с EXPOSE в Dockerfile)
  name: http                      # Имя порта