name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle', '**/gradle.lockfile') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make gradlew executable
        run: chmod +x ./demo/gradlew

      - name: Build with Gradle
        run: ./gradlew build --no-daemon
        working-directory: ./demo

      - name: Prepare Docker context
        run: |
          mkdir -p docker-build
          cp demo/build/libs/*.jar docker-build/app.jar  # копируем JAR
          cp demo/Dockerfile docker-build/               # копируем Dockerfile

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: docker-build
          push: true
          tags: danilkhasanov/demo:latest
          file: docker-build/Dockerfile

      - name: Connect to existing k3d cluster
        run: |
          # Устанавливаем k3d (если еще не установлен)
          curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash
          # Получаем доступ к существующему кластеру
          k3d kubeconfig get mycluster > ~/.kube/config
          kubectl cluster-info
          kubectl get nodes        

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.30.5'  # Укажите версию вашего кластера

            # 2. Настройка доступа к кластеру
      - name: Deploy to Cluster
        run: |
          # Создаем namespace если не существует
          kubectl create namespace dev --dry-run=client -o yaml | kubectl apply -f -
          
          # Деплой с явным указанием контекста
          helm upgrade --install demo ./helm \
            --kube-context=k3d-mycluster \
            --namespace dev \
            --set image.repository=danilkhasanov/demo \
            --set image.tag=latest \
            --set service.type=NodePort \
            --set service.nodePort=30080 \
            --wait \
            --timeout 5m \
            --debug