name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle', '**/gradle.lockfile') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make gradlew executable
        run: chmod +x ./demo/gradlew

      - name: Build with Gradle
        run: ./gradlew build --no-daemon
        working-directory: ./demo

      - name: Prepare Docker context
        run: |
          mkdir -p docker-build
          JAR_FILE=$(ls demo/build/libs/*.jar | head -n 1)
          cp "$JAR_FILE" docker-build/app.jar
          cp demo/Dockerfile docker-build/  

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: docker-build
          push: true
          tags: danilkhasanov/demo:latest
          file: docker-build/Dockerfile

      - name: Setup k3d access
        run: |
          # Установка k3d
          curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash
          
          # Проверка существования кластера
          if ! k3d cluster list | grep -q mycluster; then
            echo "Error: Cluster 'mycluster' not found!"
            echo "Available clusters:"
            k3d cluster list
            exit 1
          fi
          
          # Настройка доступа
          mkdir -p ~/.kube
          k3d kubeconfig get mycluster > ~/.kube/config
          chmod 600 ~/.kube/config
          
          # Проверка подключения
          kubectl config use-context k3d-mycluster
          kubectl cluster-info
          kubectl get nodes  

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Deploy to k3d cluster
        run: |
          # Создаем namespace
          kubectl create namespace dev --dry-run=client -o yaml | kubectl apply -f -
          
          # Деплой приложения
          helm upgrade --install demo ./helm \
          --kube-context k3d-mycluster \
          --namespace dev \
          --create-namespace \
          --set image.repository=danilkhasanov/demo \
          --set image.tag=latest \
          --set service.type=NodePort \
          --set service.nodePort=30080 \
          --wait \
          --timeout 5m \
          --debug

      - name: Verify deployment
        run: |
          echo "Application endpoints:"
          echo "1. NodePort: http://host.docker.internal:30080"
          echo "2. Port-forward: kubectl port-forward svc/demo 8080:80 -n dev"
          kubectl get all -n dev