name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle', '**/gradle.lockfile') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make gradlew executable
        run: chmod +x ./demo/gradlew

      - name: Build with Gradle
        run: ./gradlew build --no-daemon
        working-directory: ./demo

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -f demo/Dockerfile -t danilkhasanov/demo:${{ github.sha }} ./demo

      - name: Push Docker image
        run: |
          docker push danilkhasanov/demo:${{ github.sha }}

      - name: Setup Kubernetes config
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG_BASE64 }}" | base64 -d > $HOME/.kube/config
          
          # Проверяем содержимое конфига
          echo "=== Current kubeconfig ==="
          cat $HOME/.kube/config
          echo "========================="
          
          # Автоматически определяем первый доступный контекст
          CURRENT_CONTEXT=$(kubectl config view -o jsonpath='{.current-context}')
          if [ -z "$CURRENT_CONTEXT" ]; then
            CURRENT_CONTEXT=$(kubectl config view -o jsonpath='{.contexts[0].name}')
            kubectl config use-context $CURRENT_CONTEXT
          fi
          
          echo "Using context: $CURRENT_CONTEXT"
          chmod 600 $HOME/.kube/config

      - name: Configure Kubernetes access
        run: |
          # Проверяем доступные контексты
          echo "=== Available contexts ==="
          kubectl config get-contexts
          echo "========================="
          
          # Используем автоматически определенный контекст
          CURRENT_CONTEXT=$(kubectl config current-context)
          echo "Current context: $CURRENT_CONTEXT"
          
          # Проверяем подключение
          kubectl cluster-info
          kubectl get nodes

      - name: Deploy to Minikube (optional)
        if: github.ref == 'refs/heads/main'
        run: |
          helm upgrade --install demo ./helm \
            --kube-context=k3d-mycluster \
            --set image.repository=danilkhasanov/demo \
            --set image.tag=${{ github.sha }} \
            --namespace=default \
            --create-namespace \
            --debug
          # Можно добавить команды для деплоя через kubectl или helm, если нужно автоматизировать.