name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle', '**/gradle.lockfile') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make gradlew executable
        run: chmod +x ./demo/gradlew

      - name: Build with Gradle
        run: ./gradlew build --no-daemon
        working-directory: ./demo

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          # Сборка образа в среде k3d
          docker build -f demo/Dockerfile -t k3d-mycluster-registry:5000/demo:${{ github.sha }} ./demo
          docker push k3d-mycluster-registry:5000/demo:${{ github.sha }}

      - name: Setup Kubernetes
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG_BASE64 }}" | base64 -d > $HOME/.kube/config

          # Заменяем неработающий адрес на localhost
          sed -i 's/host.docker.internal/127.0.0.1/g' $HOME/.kube/config

          # Пробрасываем порт Kubernetes API
          kubectl port-forward service/kubernetes 6443:443 -n default --address=0.0.0.0 &
          sleep 5

          # Проверка
          kubectl cluster-info
          kubectl get nodes

      - name: Configure Kubernetes access
        run: |
          # Проверяем доступные контексты
          echo "=== Available contexts ==="
          kubectl config get-contexts
          echo "========================="
          
          # Используем автоматически определенный контекст
          CURRENT_CONTEXT=$(kubectl config current-context)
          echo "Current context: $CURRENT_CONTEXT"
          
          # Проверяем подключение
          kubectl cluster-info
          kubectl get nodes

      - name: Deploy to Minikube (optional)
        if: github.ref == 'refs/heads/main'
        run: |
          helm upgrade --install demo ./helm \
            --kube-context=k3d-mycluster \
            --set image.repository=danilkhasanov/demo \
            --set image.tag=${{ github.sha }} \
            --namespace=default \
            --create-namespace \
            --debug
          # Можно добавить команды для деплоя через kubectl или helm, если нужно автоматизировать.